GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "new blog2",
  "author": "Samarth Chandna",
  "url": "https://myurl.com",
  "likes": 100
}