GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "name": "root",
  "username": "root",
  "password": "alkshd1087aGJsh1bA"
}

###
GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "new blog",
  "author": "Samarth Chandna",
  "url": "https://myurl.com",
  "likes": 100
}